# Generated by Django 4.1.13 on 2024-11-16 14:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('columns', djongo.models.fields.JSONField()),
                ('dtypes', djongo.models.fields.JSONField()),
                ('data', djongo.models.fields.JSONField()),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
