version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - MONGODB_URI=mongodb+srv://xiaolinzzz2002:cTFSlatpEj4EBRgL@cluster0.1tytd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    extra_hosts:
      - "host.docker.internal:host-gateway"
